'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.6.1055.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True),
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)>
Partial Public Class Definitions

    Private cubeBlocksField() As DefinitionsDefinition

    Private blockPositionsField() As DefinitionsBlockPosition

    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Definition", IsNullable:=False)>
    Public Property CubeBlocks() As DefinitionsDefinition()
        Get
            Return Me.cubeBlocksField
        End Get
        Set
            Me.cubeBlocksField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("BlockPosition", IsNullable:=False)>
    Public Property BlockPositions() As DefinitionsBlockPosition()
        Get
            Return Me.blockPositionsField
        End Get
        Set
            Me.blockPositionsField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class DefinitionsDefinition

    Private idField As DefinitionsDefinitionID

    Private displayNameField As String

    Private iconField As String

    Private publicField As String

    Private cubeSizeField As String

    Private blockTopologyField As String

    Private sizeField As DefinitionsDefinitionSize

    Private centerField As DefinitionsDefinitionCenter

    Private modelOffsetField As DefinitionsDefinitionModelOffset

    Private modelField As String

    Private componentsField() As DefinitionsDefinitionComponent

    Private criticalComponentField As DefinitionsDefinitionCriticalComponent

    Private edgeTypeField As String

    Private buildTimeSecondsField As Integer

    Private inventorySizeField As DefinitionsDefinitionInventorySize

    Private pCUField As Integer

    Private isAirTightField As String

    '''<remarks/>
    Public Property Id() As DefinitionsDefinitionID
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property DisplayName() As String
        Get
            Return Me.displayNameField
        End Get
        Set
            Me.displayNameField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property Icon() As String
        Get
            Return Me.iconField
        End Get
        Set
            Me.iconField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property [Public]() As String
        Get
            Return Me.publicField
        End Get
        Set
            Me.publicField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property CubeSize() As String
        Get
            Return Me.cubeSizeField
        End Get
        Set
            Me.cubeSizeField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property BlockTopology() As String
        Get
            Return Me.blockTopologyField
        End Get
        Set
            Me.blockTopologyField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property Size() As DefinitionsDefinitionSize
        Get
            Return Me.sizeField
        End Get
        Set
            Me.sizeField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property Center() As DefinitionsDefinitionCenter
        Get
            Return Me.centerField
        End Get
        Set
            Me.centerField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property ModelOffset() As DefinitionsDefinitionModelOffset
        Get
            Return Me.modelOffsetField
        End Get
        Set
            Me.modelOffsetField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property Model() As String
        Get
            Return Me.modelField
        End Get
        Set
            Me.modelField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Component", IsNullable:=False)>
    Public Property Components() As DefinitionsDefinitionComponent()
        Get
            Return Me.componentsField
        End Get
        Set
            Me.componentsField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property CriticalComponent() As DefinitionsDefinitionCriticalComponent
        Get
            Return Me.criticalComponentField
        End Get
        Set
            Me.criticalComponentField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property EdgeType() As String
        Get
            Return Me.edgeTypeField
        End Get
        Set
            Me.edgeTypeField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property BuildTimeSeconds() As Integer
        Get
            Return Me.buildTimeSecondsField
        End Get
        Set
            Me.buildTimeSecondsField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property InventorySize() As DefinitionsDefinitionInventorySize
        Get
            Return Me.inventorySizeField
        End Get
        Set
            Me.inventorySizeField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property PCU() As Integer
        Get
            Return Me.pCUField
        End Get
        Set
            Me.pCUField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property IsAirTight() As String
        Get
            Return Me.isAirTightField
        End Get
        Set
            Me.isAirTightField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class DefinitionsDefinitionID

    Private typeIdField As String

    Private subtypeIdField As String

    '''<remarks/>
    Public Property TypeId() As String
        Get
            Return Me.typeIdField
        End Get
        Set
            Me.typeIdField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property SubtypeId() As String
        Get
            Return Me.subtypeIdField
        End Get
        Set
            Me.subtypeIdField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class DefinitionsDefinitionSize

    Private xField As Integer

    Private xFieldSpecified As Boolean

    Private yField As Integer

    Private yFieldSpecified As Boolean

    Private zField As Integer

    Private zFieldSpecified As Boolean

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property x() As Integer
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property xSpecified() As Boolean
        Get
            Return Me.xFieldSpecified
        End Get
        Set
            Me.xFieldSpecified = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property y() As Integer
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property ySpecified() As Boolean
        Get
            Return Me.yFieldSpecified
        End Get
        Set
            Me.yFieldSpecified = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property z() As Integer
        Get
            Return Me.zField
        End Get
        Set
            Me.zField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property zSpecified() As Boolean
        Get
            Return Me.zFieldSpecified
        End Get
        Set
            Me.zFieldSpecified = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class DefinitionsDefinitionCenter

    Private xField As Integer

    Private xFieldSpecified As Boolean

    Private yField As Integer

    Private yFieldSpecified As Boolean

    Private zField As Integer

    Private zFieldSpecified As Boolean

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property x() As Integer
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property xSpecified() As Boolean
        Get
            Return Me.xFieldSpecified
        End Get
        Set
            Me.xFieldSpecified = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property y() As Integer
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property ySpecified() As Boolean
        Get
            Return Me.yFieldSpecified
        End Get
        Set
            Me.yFieldSpecified = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property z() As Integer
        Get
            Return Me.zField
        End Get
        Set
            Me.zField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property zSpecified() As Boolean
        Get
            Return Me.zFieldSpecified
        End Get
        Set
            Me.zFieldSpecified = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class DefinitionsDefinitionModelOffset

    Private xField As Integer

    Private xFieldSpecified As Boolean

    Private yField As Integer

    Private yFieldSpecified As Boolean

    Private zField As Integer

    Private zFieldSpecified As Boolean

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property x() As Integer
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property xSpecified() As Boolean
        Get
            Return Me.xFieldSpecified
        End Get
        Set
            Me.xFieldSpecified = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property y() As Integer
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property ySpecified() As Boolean
        Get
            Return Me.yFieldSpecified
        End Get
        Set
            Me.yFieldSpecified = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property z() As Integer
        Get
            Return Me.zField
        End Get
        Set
            Me.zField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property zSpecified() As Boolean
        Get
            Return Me.zFieldSpecified
        End Get
        Set
            Me.zFieldSpecified = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class DefinitionsDefinitionComponent

    Private subtypeField As String

    Private countField As Integer

    Private countFieldSpecified As Boolean

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Subtype() As String
        Get
            Return Me.subtypeField
        End Get
        Set
            Me.subtypeField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Count() As Integer
        Get
            Return Me.countField
        End Get
        Set
            Me.countField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property CountSpecified() As Boolean
        Get
            Return Me.countFieldSpecified
        End Get
        Set
            Me.countFieldSpecified = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class DefinitionsDefinitionCriticalComponent

    Private subtypeField As String

    Private indexField As Integer

    Private indexFieldSpecified As Boolean

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Subtype() As String
        Get
            Return Me.subtypeField
        End Get
        Set
            Me.subtypeField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Index() As Integer
        Get
            Return Me.indexField
        End Get
        Set
            Me.indexField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property IndexSpecified() As Boolean
        Get
            Return Me.indexFieldSpecified
        End Get
        Set
            Me.indexFieldSpecified = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class DefinitionsDefinitionInventorySize

    Private xField As Integer

    Private yField As Integer

    Private zField As Integer

    '''<remarks/>
    Public Property X() As Integer
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property Y() As Integer
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property Z() As Integer
        Get
            Return Me.zField
        End Get
        Set
            Me.zField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class DefinitionsBlockPosition

    Private nameField As String

    Private positionField As DefinitionsBlockPositionPosition

    '''<remarks/>
    Public Property Name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property Position() As DefinitionsBlockPositionPosition
        Get
            Return Me.positionField
        End Get
        Set
            Me.positionField = Value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
Partial Public Class DefinitionsBlockPositionPosition

    Private xField As Integer

    Private yField As Integer

    '''<remarks/>
    Public Property X() As Integer
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property Y() As Integer
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = Value
        End Set
    End Property
End Class
